name: XWiki Platform CI Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build with the XWiki Docker image
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock --entrypoint "/bin/bash" xwiki/build -c " \
            git clone https://github.com/xwiki/xwiki-platform.git && \
            cd xwiki-platform && \
            export MAVEN_OPTS='-Xmx2048m -Xms512m' && \
            vncserver :1 -geometry 1280x960 -localhost -nolisten tcp && \
            export DISPLAY=:1 && \
            /home/hudsonagent/maven/bin/mvn --no-transfer-progress install -Dmaven.test.failure.ignore -Plegacy,integration-tests,docker,snapshot \
          "
